// <auto-generated />
using System;
using CS451R_Fundraiser.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CS451R_Fundraiser.Migrations
{
    [DbContext(typeof(CS451R_FundraiserContext))]
    [Migration("20230216005252_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            NpgsqlModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS451R_Fundraiser.Models.Fundraiser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    NpgsqlPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<decimal>("Goal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail");

                    b.ToTable("Fundraisers");
                });

            modelBuilder.Entity("CS451R_Fundraiser.Models.User", b =>
            {
                //b.Property<int>("Id")
                //    .ValueGeneratedOnAdd()
                //    .HasColumnType("int");

                //NpgsqlPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));


                b.Property<string>("email")
                    .HasColumnType("text");

                NpgsqlPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("email"));

                b.Property<string>("name")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("password")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            modelBuilder.Entity("CS451R_Fundraiser.Models.Fundraiser", b =>
            {
                b.HasOne("CS451R_Fundraiser.Models.User", null)
                    .WithMany("Fundraisers")
                    .HasForeignKey("UserEmail");
            });

            modelBuilder.Entity("CS451R_Fundraiser.Models.User", b =>
            {
                b.Navigation("Fundraisers");
            });
#pragma warning restore 612, 618
        }
    }
}
